spring.application.name=dgjs_server

# 1. DB ?? ?? (??, ??, ???, ????)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dgjs_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789

# 2. ??? ???? SQL ??? ??? ???? ?? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. ??? ?? ?? ?? (??? ???? ???? ???? none ?? update? ???)
spring.jpa.hibernate.ddl-auto=update