export const dummyData = [
    {
        id: 1,
        name: "국민연금 가입자 통계 데이터",
        type: "통계",
        source: "국민연금공단 DB",
        owner: "김민준",
        createdAt: "2023-03-14",
        updatedAt: "2024-11-02",
        description:
            "전국 국민연금 가입자 수, 신규 가입, 탈퇴 현황을 지역·연령·직군별로 집계한 통계 데이터입니다. 매월 1회 배치 작업을 통해 갱신되며, 정책 수립 및 지역별 가입률 분석에 활용됩니다.",
        schema: [
            { column: "region_cd", type: "VARCHAR(10)", desc: "행정구역 코드" },
            { column: "age_group", type: "VARCHAR(10)", desc: "연령대 구간 (예: 20-29)" },
            { column: "subscriber_cnt", type: "INTEGER", desc: "가입자 수" },
            { column: "new_join_cnt", type: "INTEGER", desc: "신규 가입자 수" },
            { column: "withdraw_cnt", type: "INTEGER", desc: "탈퇴자 수" },
            { column: "stat_month", type: "DATE", desc: "통계 기준 월" },
        ],
    },
    {
        id: 2,
        name: "전국 대중교통 실시간 운행 데이터",
        type: "실시간",
        source: "국가교통정보센터 API",
        owner: "이서연",
        createdAt: "2022-07-01",
        updatedAt: "2024-06-20",
        description:
            "전국 버스 및 지하철의 실시간 위치, 지연 정보, 혼잡도를 수집한 실시간 스트리밍 데이터입니다. 5초 간격으로 갱신되며, 교통 혼잡 예측 모델의 입력 데이터로 사용됩니다.",
        schema: [
            { column: "vehicle_id", type: "VARCHAR(20)", desc: "차량 고유 식별자" },
            { column: "route_no", type: "VARCHAR(10)", desc: "노선 번호" },
            { column: "lat", type: "DECIMAL(9,6)", desc: "위도" },
            { column: "lng", type: "DECIMAL(9,6)", desc: "경도" },
            { column: "congestion_lv", type: "SMALLINT", desc: "혼잡도 레벨 (1~5)" },
            { column: "collected_at", type: "TIMESTAMP", desc: "데이터 수집 시각" },
        ],
    },
    {
        id: 3,
        name: "지방자치단체 예산 집행 현황",
        type: "재무",
        source: "e나라도움 연계",
        owner: "박지훈",
        createdAt: "2023-01-10",
        updatedAt: "2024-09-15",
        description:
            "전국 지자체별 세출 예산 편성 및 집행률을 부서·사업 단위로 정리한 재무 데이터입니다. 분기별로 갱신되며, 예산 집행률 모니터링 대시보드의 기반 데이터로 사용됩니다.",
        schema: [
            { column: "local_gov_cd", type: "VARCHAR(10)", desc: "지자체 코드" },
            { column: "dept_name", type: "VARCHAR(50)", desc: "담당 부서명" },
            { column: "budget_amt", type: "BIGINT", desc: "편성 예산액 (원)" },
            { column: "executed_amt", type: "BIGINT", desc: "집행 금액 (원)" },
            { column: "exec_rate", type: "DECIMAL(5,2)", desc: "집행률 (%)" },
            { column: "quarter", type: "VARCHAR(6)", desc: "기준 분기 (예: 2024Q3)" },
        ],
    },
    {
        id: 4,
        name: "공공 와이파이 이용자 로그",
        type: "로그",
        source: "통신3사 제공",
        owner: "최유진",
        createdAt: "2021-11-23",
        updatedAt: "2024-03-30",
        description:
            "전국 공공 와이파이 접속 지점(AP)의 이용자 접속·해제 로그입니다. 개인 식별 정보는 비식별화 처리되어 있으며, 유동 인구 분석 및 AP 증설 우선순위 산정에 활용됩니다.",
        schema: [
            { column: "ap_id", type: "VARCHAR(20)", desc: "AP(접속 지점) 식별자" },
            { column: "session_id", type: "VARCHAR(32)", desc: "세션 고유 식별자 (비식별)" },
            { column: "connect_ts", type: "TIMESTAMP", desc: "접속 시각" },
            { column: "disconnect_ts", type: "TIMESTAMP", desc: "해제 시각" },
            { column: "data_usage_mb", type: "DECIMAL(10,2)", desc: "사용 데이터량 (MB)" },
        ],
    },
    {
        id: 5,
        name: "스마트팜 환경 센서 데이터",
        type: "센서",
        source: "IoT 게이트웨이",
        owner: "정하늘",
        createdAt: "2024-02-05",
        updatedAt: "2024-12-01",
        description:
            "전국 스마트팜 시범 농가에 설치된 IoT 센서로부터 수집한 온도, 습도, 토양 수분, CO2 농도 데이터입니다. 1분 간격으로 수집되며, 작물 생육 예측 모델 학습에 사용됩니다.",
        schema: [
            { column: "farm_id", type: "VARCHAR(15)", desc: "농가 고유 식별자" },
            { column: "sensor_type", type: "VARCHAR(20)", desc: "센서 종류 (온도/습도/토양/CO2)" },
            { column: "value", type: "DECIMAL(8,2)", desc: "측정값" },
            { column: "unit", type: "VARCHAR(10)", desc: "측정 단위 (℃, %, ppm 등)" },
            { column: "measured_at", type: "TIMESTAMP", desc: "측정 시각" },
        ],
    },
];
